### ISSUE TITLE
Cannot login as admin

### ISSUE THREAD

**Issue by duongch4** [tabsteveyang/MERN-jwt-authentication-boilerplate#1]
Hi there, 

Thank you for creating this repo.
I have tried to follow your instruction, and I believe my local MongoDB is connected to the server successfully (console.log to my screen).

I created an admin user like this (according to the schema) in the User collection:
{"_id":"5b361643e347d13bc8919c29",
"name":"Admin",
"pic":"someBinString",
"email":"test@outlook.com",
"password":"adminPass",
"lastupload":"2018-06-29T07:00:00.000Z",
"settings":{"language":"EN","session_card_limit":30},
"privilige":{"isActivate":true,"setting":true,"enroll":true,"create":true,"play":true,"isAdmin":true},
"tokens":["blha"]
}

but I cannot log in when entering the email and password info.

Did I create the admin information wrongly? It would be a great help if you can give me the template for the admin information. Also I dont know what type is "enrollment" field so I commented that field out, it would be helpful if you can provide me that information as well.

Thank you very much for your help.

**Comment by tabsteveyang** [comment]
Hi duongch4,

Sorry for the wrong instruction. I just notice that it won't work by inserting a user using the MongoDB prompt, because the password should be hashed after the user is created, but creating a user by the prompt will not go through the hashing process, so the password will stay unhashed and it can't match when we try to log in a user.

I update some part of the repo including the instruction, please clone the repo and try again. I walked through the steps once and it should work now.

Thank you for reporting the issue, I really appreciate that!

**Comment by duongch4** [comment]
Thank you for fixing it. I can log in now :D I will close the issue here.

PS: I still hope that you can implement a more appropriate set up for the admin functionality though.
